spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:clevercrm}
    username: ${DB_USER:clever}
    password: ${DB_PASSWORD:clever}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
