version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: clevercrm
      POSTGRES_USER: clever
      POSTGRES_PASSWORD: clever
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: clevercrm
      DB_USER: clever
      DB_PASSWORD: clever
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
